// src/frontend/components/Page/View.svelte
<script>
	import { onMount } from "svelte";
	import * as api from "frontend/api.js";
	import { highlightRange } from "frontend/lib/highlight/higlight-dom-range";
	import { fromRange, toRange } from "dom-anchor-text-position";

	// props
	export let pageId;

	// constants

	const colorToCSS = {
		"red": "highlight-red",
		"green": "highlight-green",
		"blue": "highlight-blue",
		"yellow": "highlight-yellow"
	}

	// state
	let pageDetail;
	let pageContent;

	const addAnnotation = async (pageId, selection, color = "red") => {
		if (selection == null) {
			console.error("Attempted to add annotation when selection is null");
			return
		}

		const range = selection.getRangeAt(0);
		// need to calculate textpos before highlight, otherwise the position will be messed up
		// when try to highlight on re-load
		const textPos = fromRange(document.body, range);
		const [highlightElements, removeHighlights] = highlightRange(range, 'span', {class: colorToCSS[color]});
		// save it
		const resp = await api.createAnnotation(
			{coordinate: textPos,
				page_id: pageId})
			.catch(err => console.error("Failed to add annotaiton: ", err));
		return highlightElements;
	}

	$ : if (pageDetail) {
		pageDetail.annotations.forEach(annotation => {
			const range = toRange(document.body, annotation.coordinate);
			const [highlightNodes, removeHighlights] = highlightRange(range, 'span', {class: colorToCSS[annotation.color]});
		});
	}

	onMount(() => {
		api.getPage(pageId)
			.then(resp =>pageDetail = resp.data);

		api.getPageContent(pageId)
			.then(resp => pageContent = resp.data);

		document.addEventListener("mouseup", () => {
			const selection = window.getSelection();
			if (!selection.isCollapse) {
				const boundingRect = selection.getRangeAt(0).getBoundingClientRect();
				addAnnotation(pageId, selection);
			}
			else {
			}
		});
	});

</script>

{#if pageContent}
<div id="page-content">
	{@html pageContent}
</div>
{:else}
<div>Loading...</div>
{/if}

<style>
	#page-content {
		width: 100%;
		positiion: relative;
	}

	/* highlight colors */
	:global(.highlight-red) {
		color: red;
	}

	:global(.highlight-green) {
		color: green;
	}

	:global(.highlight-blue) {
		color: blue;
	}

	:global(.highlight-yellow) {
		color: yellow;
	}
</style>

// src/frontend/components/Page/View.tsx
// @ts-nocheck
// we don't use iframe to show
// return the dom inside iframe
import { useRef, useState, useEffect } from "react";
import { TPage, TAnnotation } from "api/types";
import { api, getStaticPage, addAnnotation } from "api";

import highlightRange from "lib/highlight/higlight-dom-range";
import { fromRange, toRange } from "dom-anchor-text-position";

interface Props {
  page: TPage;
}

const colorToCSS = {
  "red": "text-red-400",
  "green": "text-green-400",
  "blue": "text-blue-400",
  "yellow": "text-yellow-400"
}

const addHighlight = (pageId: number, selection: window.Selection, color = "red") => {
  const range = selection.getRangeAt(0);
  // need to calculate textpos before highlight, otherwise the position will be messed up
  // when try to highlight on re-load
  const textPos = fromRange(document.body, range);
  const highlightElements = highlightRange(range, 'span', {class: colorToCSS[color]});
  console.log("Elements: ", highlightElements);
  // save it
  addAnnotation(
    {coordinate: textPos,
      page_id: pageId})
    .catch(err => console.error("Failed to add annotaiton: ", err));
  return highlightElements;
}

const PageView = (props: Props) => {
  const { page } = props;
  const [ content, setContent ] = useState<string>("");
  const contentDiv = useRef(null);

  useEffect(() => {
    document.addEventListener("mouseup", () => {
      const selection = window.getSelection();
      if (!selection.isCollapsed) {
        addHighlight(page.id, selection);
      }
    });
    // download the html as raw string and render it
    api.get(getStaticPage(page.path))
      .then(resp => {
        setContent(resp.data);
        page.annotations.forEach((annotation: TAnnotation) => {
          const range = toRange(document.body, annotation.coordinate);
          highlightRange(range, 'span', {class: colorToCSS[annotation.color]});
        })
      })
      .catch(e => console.error("Failed to get static page: ", e));
  }, [])

  return (<div className="">
    <div>
      <h3 className="text-red-400">sup sup sup</h3>
    </div>
    <div className="w-full relative" ref={contentDiv} dangerouslySetInnerHTML={{__html: content}}></div>
  </div>)
}

export default PageView;
